# Generated by Django 6.0.6 on 2026-07-07 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0004_alter_complaint_station'),
        ('users', '0003_remove_user_state_alter_user_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='city',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='stations', to='complaints.city'),
        ),
    ]
