# Generated by Django 6.0.6 on 2026-07-06 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('brand', models.CharField(choices=[('Apple', 'Apple'), ('Samsung', 'Samsung'), ('OnePlus', 'OnePlus'), ('Xiaomi', 'Xiaomi'), ('Google', 'Google'), ('Motorola', 'Motorola'), ('Vivo', 'Vivo'), ('Oppo', 'Oppo'), ('Realme', 'Realme'), ('Other', 'Other')], max_length=50)),
                ('desc', models.TextField()),
                ('case', models.CharField(choices=[('S', 'Stolen'), ('L', 'Lost')], max_length=1)),
                ('date_of_incidence', models.DateTimeField(blank=True, null=True)),
                ('filed_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('filed', 'Filed'), ('pending_verification', 'Pending Verification'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('under_investigation', 'Under Investigation'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='filed', max_length=30)),
                ('rejection_reason', models.CharField(blank=True, max_length=100)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='complaints', to='complaints.city')),
            ],
        ),
    ]
