# Generated by Django 6.0.6 on 2026-07-07 10:27

import complaints.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'Cities'},
        ),
        migrations.AlterField(
            model_name='complaint',
            name='date_of_incidence',
            field=models.DateTimeField(blank=True, null=True, validators=[complaints.models.validate_not_future_day]),
        ),
    ]
