# Generated by Django 6.0.6 on 2026-07-29 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='complaints/'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('pending_verification', 'Pending Verification'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('under_investigation', 'Under Investigation'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='filed', max_length=30),
        ),
    ]
