# Generated by Django 6.0.6 on 2026-07-07 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0003_alter_city_options_alter_complaint_date_of_incidence'),
        ('users', '0003_remove_user_state_alter_user_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='users.station'),
        ),
    ]
