# Generated by Django 6.0.6 on 2026-07-30 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0005_complaintimages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ComplaintImages',
            new_name='ComplaintImage',
        ),
    ]
