# Generated by Django 6.0.6 on 2026-07-30 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0006_rename_complaintimages_complaintimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaintimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='complaints/', verbose_name='url'),
        ),
    ]
