# Generated by Django 6.0.6 on 2026-07-31 01:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0007_alter_complaintimage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplaintFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='complaints/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpeg', 'jpg'])])),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='complaints.complaint')),
            ],
        ),
        migrations.DeleteModel(
            name='ComplaintImage',
        ),
    ]
