# Generated by Django 6.0.6 on 2026-07-02 17:05

import complaints.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_alter_complaint_date_of_incidence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='date_of_incidence',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='owner',
            field=models.ForeignKey(default=complaints.models.User.get_default_user, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
