# Generated by Django 6.0.6 on 2026-07-26 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_img',
            field=models.ImageField(blank=True, default='users/profile.webp', null=True, upload_to='users/'),
        ),
    ]
