# Generated by Django 6.0.6 on 2026-07-10 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0004_alter_complaint_station'),
        ('users', '0004_alter_station_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='city',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='station', to='complaints.city'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
