# Generated by Django 6.0.6 on 2026-07-16 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0004_alter_complaint_station'),
        ('users', '0005_alter_station_city_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='city', to='complaints.city'),
        ),
    ]
